version: "3.9"

services:
  web:
    build: .
    image: neu-scholar-backend:latest
    pull_policy: never
    container_name: nsa-agent
    ports:
      - "8014:8014"
    environment:
      MONGODB_URI: ${MONGODB_URI}
      MONGODB_DB: ${MONGODB_DB:-fitneu}
      PORT: ${PORT:-8014}
    restart: unless-stopped